# Generated by Django 6.0.3 on 2026-03-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_refreshtoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='refreshtoken',
            new_name='dashboard_r_user_id_89a6d7_idx',
            old_name='dashboard_r_user_id_revoked_idx',
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
