# Generated by Django 6.0.5 on 2026-06-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_payment_currency_order_refresh_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlumeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('purpleair', 'PurpleAir'), ('eccc_rdaqa', 'ECCC RDAQA')], default='purpleair', max_length=16)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('sensor_count', models.IntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['source', '-captured_at'], name='dashboard_p_source_13a3a3_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'captured_at'), name='uniq_plumeframe_source_captured')],
            },
        ),
    ]
